<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <!-- NuGet Packaging Properties -->
    <PackageId>CountryPicker.Blazor</PackageId>
    <Version>1.1.0</Version>
    <Authors>Marietta</Authors>
    <Company>Open Source</Company>
    <Description>A lightweight, high-performance, and beautifully styled CountryPicker component for Blazor, ported from the popular country_picker Flutter package by Daniel Ioannou. Features searchable dropdown combobox, customizable favorites, exclusions, and dialing codes, using zero-asset native emoji flags.</Description>
    <PackageTags>blazor country-picker phone-code flag-emoji country razor-components rcl</PackageTags>
    <RepositoryUrl>https://github.com/marietta-a/country-picker</RepositoryUrl>
    <PackageProjectUrl>https://github.com/marietta-a/country-picker</PackageProjectUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryType>git</RepositoryType>
    <Title>A lightweight, high-performance, and beautifully styled reusable Country, State, and City Picker component library for Blazor </Title>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="countries.json.br" Condition="Exists('countries.json.br')" />
	</ItemGroup>


	<ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
  </ItemGroup>

</Project>
